name: Backend CI

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build & Test
        run: mvn clean verify

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: backend/target/*.jar

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/insurance-backend:${{ github.sha }}
            ${{ secrets.DOCKER_PASSWORD }}/insurance-backend:latest